Roblox Oct 2021 73 hours outage
danluu/post-mortems pull request #179
Opened 2022-01-21 08:08 UTC by asm72

2022-01-24 02:25 UTC, icco requested changes

2022-01-24 02:25 UTC, icco commented on README.md
> +[Roblox](https://blog.roblox.com/2022/01/roblox-return-to-service-10-28-10-31-2021/) Roblox end Oct 2021 73 hours outage. Issues with Consul streaming and BoltDB.
We need a period after the link.

2022-01-24 07:18 UTC, asm72 commented on README.md
> +[Roblox](https://blog.roblox.com/2022/01/roblox-return-to-service-10-28-10-31-2021/) Roblox end Oct 2021 73 hours outage. Issues with Consul streaming and BoltDB.
Thanks

2022-01-26 14:14 UTC, icco approved these changes

2022-01-26 14:14 UTC, merged