Add note about inclusion in the VOID
danluu/post-mortems pull request #186
Opened 2022-03-14 21:52 UTC by lawrencejones

The VOID has included all the post-mortems from this list, including
many others.

Anyone visiting this list would probably benefit from knowing about the
VOID, so add a note to help them find it.

2022-03-14 22:17 UTC, danrl commented
I was asked to approve this PR. Although our names are similar and both Dan and I work in the same industry, I don't have any power here.

FWIW, without power or authority, I approve this PR. :) 

Also: Hi @danluu 👋

2022-03-14 22:45 UTC, lawrencejones commented
:joy: this interaction confused me much more than it should have!

<img width="1195" alt="Screenshot 2022-03-14 at 15 45 09" src="https://user-images.githubusercontent.com/3518874/158273041-3cd0bd75-7142-4c47-854e-25a662438e73.png">

2022-05-01 15:53 UTC, icco requested changes

2022-05-01 15:53 UTC, icco commented on README.md
> +> Database (https://www.thevoid.community/) if you wish to browse them there.
We have a list of other postmortems at the bottom of this document. Please move this comment to there.

2022-06-05 18:48 UTC, icco commented
No update, closing.

2022-06-05 18:48 UTC, closed without merging